// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Paste struct {
	ID               string
	Filename         *string
	DetectedLanguage string
	Content          string
	SizeBytes        int64
	ViewCount        int64
	ExpiresAt        string
	CreatedAt        string
}
