// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: paste.sql

package sqlc

import (
	"context"
)

const createPaste = `-- name: CreatePaste :exec
INSERT INTO paste (id, filename, detected_language, content, size_bytes, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type CreatePasteParams struct {
	ID               string
	Filename         *string
	DetectedLanguage string
	Content          string
	SizeBytes        int64
	ExpiresAt        string
	CreatedAt        string
}

func (q *Queries) CreatePaste(ctx context.Context, arg CreatePasteParams) error {
	_, err := q.db.ExecContext(ctx, createPaste,
		arg.ID,
		arg.Filename,
		arg.DetectedLanguage,
		arg.Content,
		arg.SizeBytes,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredPastes = `-- name: DeleteExpiredPastes :exec
DELETE
FROM paste
WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredPastes(ctx context.Context, timestamp string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPastes, timestamp)
	return err
}

const getPaste = `-- name: GetPaste :one
SELECT id, filename, detected_language, content, size_bytes, view_count, expires_at, created_at
FROM paste
WHERE id = ?1
`

func (q *Queries) GetPaste(ctx context.Context, id string) (Paste, error) {
	row := q.db.QueryRowContext(ctx, getPaste, id)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.DetectedLanguage,
		&i.Content,
		&i.SizeBytes,
		&i.ViewCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE paste
SET view_count = view_count + 1
WHERE id = ?1
`

func (q *Queries) IncrementViewCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementViewCount, id)
	return err
}
